### ISSUE TITLE
Crouching Rancor Sync not working

### ISSUE THREAD

**Issue by jmscratch** [danpaulson/swgoh.gg.public#89] opened 2017-11-02 14:49 UTC
I use crouching Rancor mod manager daily but haven't been able to in a while, keep getting the following error. Is there anything yall can do to make this work again? Error message is below.

"Sorry, can't fetch your data : swgoh.gg's rate limit hit
Please try again later"

**Comment by DilatoryCheetah** [comment] 2017-11-02 15:03
swgoh.gg has started blocking calls from a single site as they had previously warned they would do.  What is needed is an API call for individual users that will expose this data and reduce the load on the servers.

**Comment by jmscratch** [comment] 2017-11-02 18:33
so basically, we are SOL until one of the devs has time to work on it. Just
wondering if they are working on it or not at all.

Jason Mower
jmo101@gmail.com

**Comment by danpaulson** [comment] 2017-11-02 18:38
We’re working on scaling and data issues currently. No ETA on supporting third party consumers of data.

**Comment by jmscratch** [comment] 2017-11-02 18:42
gotcha, thanks for the reply. anything we can do to help just let us know. Might be easier for yall to just modify the mods manager on your own site to include a sorting and rating feature like crouching rancor had, so you can see how a mod fairs against others in the database, Thanks again, love the site, so helpful!

**Comment by danpaulson** [comment] 2017-11-02 18:50
You can definitely sort your mods on the site by stats, we have plans for aggregating overall value as well.

**Comment by danpaulson** [comment] 2017-11-02 18:51
https://swgoh.gg/u/dan/mods/?stat2_5=1 For example

**Comment by jmscratch** [comment] 2017-11-02 18:53
Well, I was referring to overall sort by best mod which would be part of the aggregating you mentioned. Thanks!

**Comment by DilatoryCheetah** [comment] 2017-11-02 20:10
The part that I miss from CR tools is the ability to create a squad and assign mods to everyone on the squad.  Then generate a report telling you who to take mods off of to put on your squad.

**Comment by cchesko** [comment] 2017-11-05 18:30
If you could fix the filter pagination bug, it would make it a lot easier for us to use this site to search mods.  

Also, I never see unassigned mods, but that may be related to the above bug?

**Comment by DilatoryCheetah** [comment] 2017-11-05 19:08
swgoh.gg never showed unassigned mods.  Crouching Rancor cached the mod data so any mods that it had seen previously, but no longer sees, it assumes is unassigned.

**Comment by CrouchingRancor** [comment] 2017-11-10 15:53
Hey,

Just landed on this issue. While I perfectly understand you will provide your own agregating tools, do you think possible to set up a solution for the user base in the meantime ? 

I couldn't get any official rate limiting / best practice to reduce the load on your side. I tried to upgrade the caching of each users' mods to 24h, but even this timer wasn't enough to provide a working solution.

Any clarification/help would be much appreciated ! At least to inform correctly the users.
 
Thanks !

**Comment by DilatoryCheetah** [comment] 2017-11-10 16:59
I guess one workaround would be to let users manually upload their mods to your site.  swgoh.gg isn't blocked for an individual user so we can grab the data ourselves and give it to you.

**Comment by danpaulson** [comment] 2017-11-10 17:03
The issue is more a bandwidth problem - ours is currently zero to work on any features or fixes. The current rate limits are in place to ensure the site can continue running for everyone until such a time exists that we can work on this project. TLDR; we are in pure maintenance mode.

**Comment by BK024** [comment] 2017-11-30 17:50
@DilatoryCheetah I am making a tool that does just that. It uses the moddata from swgoh.gg. So unfortunately no way to get to the unassigned mods, and I also would have the same problem as @CrouchingRancor when it comes to requests at the site. Still, I could easily make an executable you can use on your own computer that downloads your dbase of mods once a day and then you give that to me for an analysis. My tool can't be on a website for the moment, since the number of calculations is huge. It need to run locally and needs optimization for every analysis that is made. I'm looking for people to test the tool with. So if you are interested in helping me (and getting some useful info about your mods along the way) send me a reply.

**Comment by jmscratch** [comment] 2017-12-01 14:17
@BK024 count me in.

**Comment by ThreePeak** [comment] 2018-01-19 06:50
I completely understand there is multiple issues involved, and that the team at swgoh.gg has a right to choose how their invention (and by who) is used.  I'm certain there is a valid complaint to having everyone using your hard work for their own tools...and you guys get stuck on the hook for that bandwidth and costs, without anything to show for it.  Having said that, the web dev at crouching rancor has made every effort to minimize any impact, has been polite, and even posted a plea on his site for people to make sure they clicked on ads on swgoh.gg  to generate revenue  for them.  All to try and make sure his tool didn't screw you guys.  Swgoh.gg and the team behind it are freaking awesome for what they have accomplished.  There is however a bad perception around this.  A double standard from appearences.  Because every single tool I've come across uses, and continues to pull their data from swgoh. Gg.  Only CR seems to have a block.  Yes, features overlap in some cases, but any user of crouching rancor is also a user of swgoh. Gg.  The use of one does not preclude the other.  So be fair here, be consistent.  You have a limit on bandwidth? Tell them the cap or set some standards.  Don't want people using your data? So be it,  but make it apply to all.  Your sites should be affiliates!  You should be working together.  Not acting like a corporation.  Also, to point out, you basically say we have no bandwidth or people to fix this issue. PS: we are in maintain mode.  Lastly, I want to disclose I have absolutely ZERO affiliation, interest or stake with CR.  This is an issue that I feel needs to be said.  PS: does EA cut you off when you use their servers to pull our data?

**Comment by ThreePeak** [comment] 2018-01-19 06:57
@BK024 can I get in on your tool testing?

**Comment by danpaulson** [comment] 2018-01-19 13:25
Let’a hit a few points:

1 - We don’t have a blacklist, CR is subject to the same ratelimiting as every other app that pops up. We have whitelisted a precious few users (I believe the number is three) that use the data for spreadsheets and low impact features. We began implementing these ratelimits when site performance reliability started to diminish.

2 - Our issue with a lot of sites that pop up is that they slap ads on what is ultimately our work right out of the gate. This project is 100% a side project; that’s literally thousands of hours of our free time poured into this. We will absolutely defend against standing on that effort and attempting to monetize it.

3 - That said, we are willing to work with just about anyone. To that point, I’ve had discussions with the CR dev to possibly join the team working on .GG. I can’t say if he will accept, but I don’t know how to be more open to collaboration than by literally allowing devs to work on the project.

Typing this on a phone, so may have missed some points. Feel free to ask any other questions about why we operate as we do - TLDR is that we are being as generous with our time and resources to the community as humanly possible.

**Comment by CrouchingRancor** [comment] 2018-01-19 13:45
Hey, backing up on Dan : we're in contact, just we both have limited time to work fast enough on this, being side projects for all of us.
If my website hits rate limits, it's due to the nature of mods : many pages have to be visited at once for every single player profile. That's a huge load.
My "warning" pop-up is probably not well written (it's been added in a rush), but it's just there to help understand why most of the users can't fetch their profile. I get it can confuse the users. I'll try to find some time to rephrase it.

**Closed** 2018-02-07 22:41 UTC
