### ISSUE TITLE
[Feature Request] Add GP over time plot to User and Guild's pages

### ISSUE THREAD

**Issue by brunoalr** [danpaulson/swgoh.gg.public#166] opened 2018-02-22 16:42 UTC
When I was a Guild Officer, I was interested in keeping track on my guildmates progress. One way of doing so would be to plot the GP over time.

Ideally, it would be nice to have a complete history, but a fixed time window (say 30 days as it's currently done with Player Arena Rank on the User's page) will be just fine to know which guild member are not evolving and are canditates to be expelled.

**Comment by brunoalr** [comment] 2018-03-08 15:12
@danpaulson @scoot1585 thoughts?

**Comment by dwcullop** [comment] 2018-03-08 21:28
I think this would be a very welcome feature.  I'm currently tracking GP histories in a spreadsheet and have to copy/paste the latest GPs on weekly basis.  If storage and/or volume of records is an issue, this is not something that needs to be tracked daily because GP changes slowly.  For that same reason, it would be valuable to have that data tracked over a longer period than 30 days.

In other words, I would rather have 24 weekly records that cover the past six months than 30 daily records that cover the past month.

**Comment by FingolfinTEK** [comment] 2018-03-13 19:00
+1 from me and all the officers in our guild :D

**Comment by FingolfinTEK** [comment] 2018-03-13 19:02
Duplicate of #26 https://github.com/danpaulson/swgoh.gg.public/issues/26

**Comment by brunoalr** [comment] 2018-03-13 19:46
@FingolfinTEK thanks for noticing that this a duplicate. Should we move the discussion to the original issue?

**Comment by danpaulson** [comment] 2018-03-16 02:16
Going to close that as dupe of #26 - still on our radar but not imminent.

**Closed by danpaulson** 2018-03-16 02:16 UTC

**Comment by brunoalr** [comment] 2018-03-16 12:51
@danpaulson thx!
