### ISSUE TITLE
Guild unit search no longer working. 

### ISSUE THREAD

**Issue by scuba75** [danpaulson/swgoh.gg.public#98] opened 2017-11-24 05:54 UTC

**Comment by prasanthmathialagan** [comment] 2017-11-24 08:01
I am facing the same issue

https://swgoh.gg/g/11097/swgoh-guild-raiders/unit-search/

On clicking the "Select Unit" button, no response is received. I did a bit of debugging.
I see there is a call to "https://swgoh.gg/api/guilds/11097/units/" but only partial response is returned and keeps waiting for a long time when I tried with curl

**Comment by j0rdanit0** [comment] 2017-11-25 04:01
I have the same issue with my guild. This api call returns a partial JSON response, instead of the full response body.

https://swgoh.gg/api/guilds/3087/units/

**Comment by danpaulson** [comment] 2017-11-25 04:27
This should be fixed now - caused by a refactor of code and more or less endless caching of JS variations on that page lead to running out of disk space.

**Closed by danpaulson** 2017-11-25 04:27 UTC
