### ISSUE TITLE
Character, Squads, mods etc. not visible!

### ISSUE THREAD

**Issue by Deantron** [danpaulson/swgoh.gg.public#186] opened 2018-03-03 18:41 UTC
https://swgoh.gg/u/deantron/

My ships, characters, mods... are not visible anymore! And sync stopped working for a couple of days!

Waht to do?

**Comment by Danimal126** [comment] 2018-03-03 19:52
Same issue since the update.

https://swgoh.gg/u/danimal126/mods/

**Comment by scoot1585** [comment] 2018-03-03 20:32
we know what the problem is, we are figuring out a solution, thanks for the report

**Comment by scoot1585** [comment] 2018-03-04 02:32
This should be fixed, let us know if a manually resync or your next automatic one doesn't fix it.

**Closed by scoot1585** 2018-03-04 02:32 UTC
Labels: bug
