### ISSUE TITLE
Mods, ships, Characters - all missing from swgoh.gg

### ISSUE THREAD

**Issue by UdaiKwicklee** [danpaulson/swgoh.gg.public#187] opened 2018-03-03 19:05 UTC
https://swgoh.gg/u/udaikwicklee/

I was using the mod page just last night, so I am active. ( I noted a similar case was closed when the account was deemed inactive).

I can see my profile and my 'gear needed' but i see '0' for my mods, ships and characters.

https://swgoh.gg/u/udaikwicklee/mods/
![image](https://user-images.githubusercontent.com/37025606/36938145-6a999f0c-1f15-11e8-8019-e5af4c0dac97.png)

https://swgoh.gg/u/udaikwicklee/ships/
![image](https://user-images.githubusercontent.com/37025606/36938150-799296a8-1f15-11e8-9664-715ac42ab635.png)

https://swgoh.gg/u/udaikwicklee/collection/
![image](https://user-images.githubusercontent.com/37025606/36938161-8734de88-1f15-11e8-93ed-c731fba91be8.png)

As you can see it is recently 'updated' and I have told it to sync again. Anything you can do?
I also used http://swgohmods.com last night (which syncs to swgoh.gg, I believe) could that have corrupted things somehow?

**Comment by Pikkupomo** [comment] 2018-03-03 19:44
Same problem here and for all our guildies. No mods, characters, ships.

**Comment by scoot1585** [comment] 2018-03-03 20:31
we know what the problem is, we are figuring out a solution, thanks for the report

**Comment by UdaiKwicklee** [comment] 2018-03-03 20:35
Much appreciated.

**Comment by TheDude182** [comment] 2018-03-03 20:59
I have been experiencing the same issue.  https://swgoh.gg/u/thedude182/

**Comment by scoot1585** [comment] 2018-03-04 02:32
This should be fixed, let us know if a manually resync or your next automatic one doesn't fix it.

**Closed by scoot1585** 2018-03-04 02:32 UTC
Labels: bug

**Comment by UdaiKwicklee** [comment] 2018-03-04 11:51
Yep, fixed. TYVM
