### ISSUE TITLE
profile

### ISSUE THREAD

**Issue by jharbour5** [danpaulson/swgoh.gg.public#42] opened 2017-10-01 01:15 UTC
the address for my profile changed. it was https://swgoh.gg/u/jharbour#3192 - now it is https://swgoh.gg/u/jharbour%233192/

**Comment by scoot1585** [comment] 2017-10-02 15:56
The pound sign in web terms is a reserved character.  it signifies a URL fragment.  If you tried to use it, it would build an invalid URL since you would actually be attempting to go to `https://swgoh.gg/u/jharbour` and then you would go to fragment `#3192` on the page which wouldnt exist so it wouldnt do anything

I am going to close this, since it is working as intended.

**Closed by scoot1585** 2017-10-02 15:56 UTC

**Comment by jharbour5** [comment] 2017-10-02 17:52
Can we change the name on my profile to just jharbour ?

**Comment by scoot1585** [comment] 2017-10-02 18:56
yup, I updated it to just `jharbour` now.  should be good to go.

**Comment by jharbour5** [comment] 2017-10-02 22:59
Thank you
