### ISSUE TITLE
Sort By Arena Average on Guild Page Incorrect Order

### ISSUE THREAD

**Issue by sdthornton** [danpaulson/swgoh.gg.public#1] opened 2017-04-21 02:08 UTC
It looks like the sorting on the "arena average" column of a guild page (e.g. https://swgoh.gg/g/122/the-allidnce-pi/) is treating the numbers as text, rather than int, and it orders according to the first number rather than value of the whole number.

For instance, `9, 33, 2, 111` would become `111, 2, 33, 9`.

**Comment by scoot1585** [comment] 2017-04-22 04:23
what browser and OS are you using?  I can't reproduce this on any major browser.  I checked multiple guilds and multiple columns and everything looked correct.  

Can you also please a URL for a guild this happens on?

**Comment by sdthornton** [comment] 2017-04-22 17:34
Interesting, I can't reproduce it now! I'm running latest Chrome of OSX, but I dual boot on windows (Chrome as well) so I'll check on my windows side later. Thanks for looking into this!

**Comment by scoot1585** [comment] 2017-04-27 04:01
If ya can't find a reproducible test case, I am going to close this after this weekend.  You can always start a new ticket if it pops back up!

**Closed** 2017-05-01 15:09 UTC
Labels: bug
